import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, readdir, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
test('file API and two clients preserve edits and reject unsafe writes', async () => {
 const dir=await mkdtemp(join(tmpdir(),'coppy-test-'));
 const port=19000+Math.floor(Math.random()*10000), base=`http://127.0.0.1:${port}`;
 const server=spawn(process.execPath,['--experimental-sqlite','server.js'],{env:{...process.env,PORT:String(port),COPPY_DB:join(dir,'db'),COPPY_FILES:join(dir,'files')},stdio:'ignore'});
 try {
  let ready=false;for(let i=0;i<100;i++){try{await fetch(base+'/api/files');ready=true;break}catch{await new Promise(r=>setTimeout(r,50))}}assert.ok(ready);
  const put=(p,b,h='')=>fetch(base+'/api/file?path='+encodeURIComponent(p),{method:'PUT',headers:{'If-Match':h},body:b});
  assert.equal((await put('../escape','bad')).status,400);
  assert.equal((await put('CON.txt','bad')).status,400);
  assert.equal((await put('folder/a.txt','initial')).status,200);
  assert.equal((await put('folder/a.txt','overwrite')).status,409);
  assert.equal((await put('FOLDER/A.txt','case')).status,409);
  assert.equal((await put('folder','collision')).status,409);
  const bin=join(dir,'client');await exec('go',['build','-o',bin,'.'],{cwd:'sync'});
  const a=join(dir,'a'),b=join(dir,'b');
  const sync=d=>exec(bin,['--once','--dir',d,base]);
  await sync(a);await sync(b);
  assert.equal(await readFile(join(b,'folder/a.txt'),'utf8'),'initial');
  await writeFile(join(a,'folder/a.txt'),'mac edit');await sync(a);await sync(b);
  assert.equal(await readFile(join(b,'folder/a.txt'),'utf8'),'mac edit');
  await writeFile(join(b,'win.txt'),'windows');await sync(b);await sync(a);
  assert.equal(await readFile(join(a,'win.txt'),'utf8'),'windows');
  await writeFile(join(a,'folder/a.txt'),'mac conflict');await writeFile(join(b,'folder/a.txt'),'win conflict');await sync(a);await sync(b);await sync(a);
  assert.equal(await readFile(join(b,'folder/a.txt'),'utf8'),'mac conflict');
  const names=await readdir(join(a,'folder'));const conflict=names.find(n=>n.includes('.conflict-'));assert.ok(conflict);
  assert.equal(await readFile(join(a,'folder',conflict),'utf8'),'win conflict');
  const binary=Buffer.from([0,255,1,128,0]);
  assert.equal((await put('binary.dat',binary)).status,200);
  assert.deepEqual(Buffer.from(await (await fetch(base+'/api/file?path=binary.dat')).arrayBuffer()),binary);
  assert.equal((await put('empty.dat','')).status,200);
  await sync(a);assert.equal((await readFile(join(a,'empty.dat'))).length,0);
  const outside=join(dir,'outside');await mkdir(outside);
  await symlink(outside,join(b,'linked'));
  assert.equal((await put('linked/escape.txt','blocked')).status,200);
  await assert.rejects(sync(b));assert.deepEqual(await readdir(outside),[]);
  await rm(join(b,'linked'));
  const bgdir=join(dir,'background');await mkdir(bgdir);
  await writeFile(join(bgdir,'from-current-folder.txt'),'current folder upload');
  await assert.rejects(exec(bin,['--once','--peer',base,'--dir',bgdir,'.']), {code:2});
  await assert.rejects(exec(bin,['--once','--peer',base,'.','extra']), {code:2});
  const launched=await exec(bin,['--peer',base,'.'],{cwd:bgdir});
  const pid=Number(launched.stdout.match(/PID (\d+)/)[1]);
  try {let received=false;for(let i=0;i<100;i++){try{await readFile(join(bgdir,'binary.dat'));received=true;break}catch{await new Promise(r=>setTimeout(r,50))}}assert.ok(received)}finally{process.kill(pid,'SIGTERM')}
  assert.equal(await (await fetch(base+'/api/file?path=from-current-folder.txt')).text(),'current folder upload');
  await rm(join(b,'win.txt'));await sync(b);assert.equal(await readFile(join(b,'win.txt'),'utf8'),'windows');
 } finally {if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}await rm(dir,{recursive:true,force:true})}
});
